redis:
  image: redis
  labels:
    io.rancher.container.hostname_override: container_name
hasher:
  image: brutus333/hasher
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
rng:
  image: brutus333/rng
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
worker:
  image: brutus333/worker:v1.0
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  links:
  - redis:redis
  - rng:rng
  - hasher:hasher
webui:
  ports:
  - 8000:80/tcp
  image: brutus333/webui
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: true
  links:
  - redis:redis
troubleshoot:
  image: brutus333/troubleshoot
  tty: true
  stdin_open: true
